### ISSUE TITLE
iPhone の PWA でアプリ名が'app'となる

### ISSUE THREAD

**Issue by tanykazy** [gdg-nara/youtuben#15]
![iPhone PWA](https://user-images.githubusercontent.com/42724767/90247262-316b2e80-de71-11ea-84ac-1af2bc9264ac.jpg)

**Comment by t-cool** [comment]
@tanykazy 
youtuben となるように修正しておきました。
ホーム画面に追加されるアイコンが、アイコンを追加するタイミングの画面のスクリーンショットで設定されてしまうので、このアイコンを youtuben のアイコンに設定したいですね。

youtuben のアイコンがないのを issue に上げておきます。
