### ISSUE TITLE
作者の表記

### ISSUE THREAD

**Issue by t-cool** [gdg-nara/youtuben#21]
@tanykazy 

[commit](https://github.com/gdg-nara/youtuben/commit/f7a1d026768cd39c165f61f143bb4ab2127b0441)

t-cool より tanykazy 氏がクリティカルな箇所の実装をされているので表記の順番を変えましたが、希望があれば随時変更します。

**Comment by tanykazy** [comment]
発案が大切なので、t-cool 先頭でいいと思いますよ!

**Comment by t-cool** [comment]
@tanykazy 
了解です！
