### ISSUE TITLE
YouTube再生ページで字幕の最後が表示されない

### ISSUE THREAD

**Issue by t-cool** [gdg-nara/youtuben#25]
現状、字幕の枠の高さは決め打ちなので、
デバイスごとに画面の高さをcalcで計算して、%で高さを調整するように修正する。

**Comment by tanykazy** [comment]
#27 別の実装を試したので、このissueが解決する場合マージしてください。

**Comment by t-cool** [comment]
ありがとうございます！
src/app/tab1/tab1.page.html が conflict してるようなので、微調整お願いしていいでしょうか。
僕が足した箇所は削除していただいて結構です。

**Comment by t-cool** [comment]
確認しました！最高です！
ありがとうございました！
