### ISSUE TITLE
Date.UTC() の第2引数

### ISSUE THREAD

**Issue by tanykazy** [gdg-nara/youtuben#4]
#3 
src/app/services/record-count.service.ts: 98
Date.UTC() の第2引数 month が +1 されている
```
static toDateTime(date: Date): number
```
この関数は Date オブジェクトを引数に取るので、Date オブジェクトの getMonth() メソッドが返す月(0-11)をそのままDate.UTC() へ渡す必要がある。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC
```
Date.UTC(year[, month[, day[, hour[, minute[, second[, millisecond]]]]]])

month
「月」を表す 0 (1 月) から 11 (12 月) までの整数値。 (ECMAScript 2016 まで、 month は必須の引数でした。 ES2017 では必須ではなくなりました。)
```

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth
```
dateObj.getMonth()
戻り値
地方時に基づき、与えた日付の「月」を表す 0 から 11 までの間の整数値。0 は 1 月、1 は 2 月、11 は 12 月に対応します。
```

**Comment by t-cool** [comment]
> この関数は Date オブジェクトを引数に取るので、Date オブジェクトの getMonth() メソッドが返す月(0-11)をそのままDate.UTC() へ渡す必要がある。

なるほどです。勉強になりました！

**Comment by tanykazy** [comment]
ぼくのの issue の出し方がまだ下手ですね。勉強します。
